config/routes.rb
Rails.application.routes.draw do
  resources :articles do
    resources :comments
  end

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  belongs_to :user
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :authenticate_user!
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = current_user.articles
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:name, :description, :domain)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET articles/1/comments
  def index
    @comments = @article.comments
  end

  # GET articles/1/comments/1
  def show
  end

  # GET articles/1/comments/new
  def new
    @comment = @article.comments.build
  end

  # GET articles/1/comments/1/edit
  def edit
  end

  # POST articles/1/comments
  def create
    @comment = @article.comments.build(comment_params)

    if @comment.save
      redirect_to(@comment.article)
    else
      render action: 'new'
    end
  end

  # PUT articles/1/comments/1
  def update
    if @comment.update(comment_params)
      redirect_to(@comment.article)
    else
      render action: 'edit'
    end
  end

  # DELETE articles/1/comments/1
  def destroy
    @comment.destroy

    redirect_to @article
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = current_user.articles.find(params[:article_id])
    end

    def set_comment
      @comment = @article.comments.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def comment_params
      params.require(:comment).permit(:name, :description, :status, :article_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Name:</strong>
    <%= article.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= article.description %>
  </p>

  <p>
    <strong>Domain:</strong>
    <%= article.domain %>
  </p>

  <p>
    <strong>User:</strong>
    <%= article.user_id %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= form_with(model: article) do |form| %>
  <% if article.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :domain, style: "display: block" %>
    <%= form.text_area :domain %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span>Articles</span>
      <%= link_to 'New Article', new_article_path, class: 'btn btn-primary' %>
    </h2>

    <% @articles.each do |article| %>
      <%= link_to article, class: 'text-decoration-none' do %>
        <div class="card article-card mb-3">
          <div class="card-body">
            <div class="mb-3">  
                <%= article.domain %>
            </div>
            <h5 class='card-title text-dark'><b><%= article.name %></b></h5>
            <p class='text-secondary'><%= article.description %></p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<%= link_to 'Back', articles_path, class: 'btn btn-secondary mb-3' %>
<div class="card">
  <div class="card-body">
    <h2 class='card-title d-flex justify-content-between mb-4'>
      <span><%= @article.name %></span>
      <div>
        <%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-light' %>
        <%= button_to 'Destroy', @article, class: 'btn btn-dark',  method: :delete, data: { confirm: 'Are you sure?' ,"turbo-method": :delete } %>
      </div>
    </h2>

    <div class="mb-4">
      <h6>Add Comments</h6>
      <%= form_for([@comment.article, @comment]) do |f| %>
        <% if @comment.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
            <% @comment.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="input-group">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter comment name...' %>
          <div class="input-group-append">
            <%= f.submit class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>

    <h4>Comments</h4>
    <% @article.comments.each do |comment| %>
      <% if comment.persisted? %>
        <div class="card mb-3">
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <span class="badge badge- mb-5"></span>
              <div>
                <%= link_to 'Edit', edit_article_comment_path(comment.article, comment), class: 'btn btn-light btn-sm' %>
                <%= button_to 'Destroy', [comment.article, comment], class: 'btn btn-dark btn-sm' , method: :delete, data: { confirm: 'Are you sure?', "turbo-method": :delete } %>
              </div>
            </div>
            <h5 class='card-title mb-2'>
              <span><%= comment.name %></span>
            </h5>
            <p><%= comment.description %></p>
          </div>
        </div>
      <% end %>
    <% end%>

  </div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@comment.article, @comment]) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>


<%= link_to 'Back', article_comments_path(@comment.article) %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Article</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comments.each do |comment| %>
  <tr>
    <td><%= comment.name %></td>
    <td><%= comment.description %></td>
    <td><%= comment.article %></td>
    <td><%= link_to 'Show', [comment.article, comment] %></td>
    <td><%= link_to 'Edit', edit_article_comment_path(comment.article, comment) %></td>
    <td><%= link_to 'Destroy', [comment.article, comment], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Comment', new_article_comment_path(params[:article_id]) %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', article_comments_path(@comment.article) %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @comment.name %>
</p>

<p>
  <b>Description:</b>
  <%= @comment.description %>
</p>

<p>
  <b>Article:</b>
  <%= @comment.article %>
</p>


<%= link_to 'Edit', edit_article_comment_path(@comment.article, @comment) %> |
<%= link_to 'Back', article_comments_path(@comment.article) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPostApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" >

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container pt-5 pb-5">
   <p class="notice"><%= notice %></p>
   <p class="alert"><%= alert %></p>
   <% if controller_name == "comments" || controller_name == "articles" %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete , data: { "turbo-method": :delete } ,  class: 'btn btn-primary mb-3' %>
   <% end %>
    <div class="card">
      <div class="card-body">
       <%= yield %>
      </div>
   </div>
  </div>
  </body>
</html>